name: MoodDiary
options:
  bundleIdPrefix: com.yourcompany
  deploymentTarget:
    iOS: "17.0"
targets:
  MoodDiary:
    type: application
    platform: iOS
    sources:
      - path: App
        excludes:
          - AppIntents.swift
          - FineTuneSheet.swift
          - Data/MoodEntry.swift
          - Data/MoodStore.swift
      - path: Shared
        excludes:
          - Intents/**
    resources:
      - App/Resources
      - Shared/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yourcompany.mood
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_FILE: App/Info.plist
        CODE_SIGN_ENTITLEMENTS: App/MoodDiary.entitlements
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 1
    # Temporarily remove widget from app build to unblock CI screenshots
    # dependencies:
    #   - target: MoodWidget
  MoodWidget:
    type: app-extension
    platform: iOS
    sources:
      - Widget
      - path: Shared
        excludes:
          - Helpers/NotificationHelper.swift
          - Store/MoodStore.swift
          - Intents/AppIntents.swift
    resources:
      - Shared/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yourcompany.mood.widget
        INFOPLIST_FILE: Widget/Info.plist
        CODE_SIGN_ENTITLEMENTS: Widget/MoodWidget.entitlements
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: "$(inherited) WIDGET_EXT"
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 1
  MoodDiaryAppOnly:
    type: application
    platform: iOS
    sources:
      - path: App
        excludes:
          - AppIntents.swift
          - FineTuneSheet.swift
          - Data/MoodEntry.swift
          - Data/MoodStore.swift
      - path: Shared
        excludes:
          - Intents/**
    resources:
      - App/Resources
      - Shared/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yourcompany.mood.apponly
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_FILE: App/Info.plist
        CODE_SIGN_ENTITLEMENTS: App/MoodDiary.entitlements
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 1
  MoodDiaryScreenshots:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests/ScreenshotsTests.swift
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yourcompany.mood.tests
    dependencies:
      - target: MoodDiary
schemes:
  MoodDiary:
    build:
      targets:
        MoodDiary: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - name: MoodDiaryScreenshots
  MoodDiaryAppOnly:
    build:
      targets:
        MoodDiaryAppOnly: all
    run:
      config: Debug