name: MoodDiary
options:
  bundleIdPrefix: com.yourcompany
  deploymentTarget:
    iOS: "17.0"
targets:
  MoodDiary:
    type: application
    platform: iOS
    sources:
      - App
      - Shared
    resources:
      - App/Resources
      - Shared/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yourcompany.mood
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - target: MoodWidget
    entitlements: App/MoodDiary.entitlements
  MoodWidget:
    type: app-extension
    platform: iOS
    sources:
      - Widget
      - Shared
    resources:
      - Shared/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yourcompany.mood.widget
        INFOPLIST_FILE: Widget/Info.plist
    entitlements: Widget/MoodWidget.entitlements
  MoodDiaryScreenshots:
    type: bundle.unit-test
    platform: iOS
    sources:
      - Tests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yourcompany.mood.tests
    dependencies:
      - target: MoodDiary
schemes:
  MoodDiary:
    build:
      targets:
        MoodDiary: all
        MoodWidget: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - name: MoodDiaryScreenshots