name: iOS Build (XcodeGen)

on:
  push:
  pull_request:

jobs:
  build:
    name: Build MoodDiary (iOS 17)
    runs-on: macos-14
    steps:
      - name: Select Xcode 16
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.*'
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install XcodeGen
        run: |
          brew update
          brew install xcodegen

      - name: Generate Xcode Project
        run: xcodegen generate

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Build for iOS Simulator
        run: |
          xcodebuild \
            -project MoodDiary.xcodeproj \
            -scheme MoodDiary \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' \
            -configuration Debug \
            build \
            CODE_SIGNING_ALLOWED=NO
      - name: Run UI snapshot tests
        run: |
          xcodebuild \
            -project MoodDiary.xcodeproj \
            -scheme MoodDiary \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' \
            -configuration Debug \
            test \
            CODE_SIGNING_ALLOWED=NO \
            | xcpretty -c || true
      - name: Collect snapshots
        run: |
          mkdir -p snapshots
          # Grab files written to tmp by tests
          ls /private/var/folders/*/*/*/T | head -n 1 | xargs -I{} sh -c 'cp -v /private/var/folders/*/*/*/T/ContentView.png snapshots/ 2>/dev/null || true; cp -v /private/var/folders/*/*/*/T/FineTuneSheet.png snapshots/ 2>/dev/null || true'
          ls -la snapshots || true
      - name: Upload snapshots
        uses: actions/upload-artifact@v4
        with:
          name: ui-snapshots
          path: snapshots
