name: iOS Build (XcodeGen)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build MoodDiary (iOS 17)
    runs-on: macos-14
    steps:
      - name: Select Xcode 16
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.*'
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install XcodeGen
        run: |
          brew update
          brew install xcodegen

      - name: Generate Xcode Project
        run: xcodegen generate

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Build for iOS Simulator
        run: |
          xcodebuild \
            -project MoodDiary.xcodeproj \
            -scheme MoodDiary \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' \
            -configuration Debug \
            build \
            CODE_SIGNING_ALLOWED=NO
      - name: Record short simulator video (app launch)
        run: |
          set -euo pipefail
          # Determine simulator build output path
          SETTINGS=$(xcodebuild -project MoodDiary.xcodeproj -scheme MoodDiary -sdk iphonesimulator -configuration Debug -showBuildSettings)
          TARGET_BUILD_DIR=$(echo "$SETTINGS" | awk -F" = " '/TARGET_BUILD_DIR/ {print $2; exit}')
          APP_PATH="$TARGET_BUILD_DIR/MoodDiary.app"
          echo "APP_PATH=$APP_PATH"
          # Boot simulator and install
          xcrun simctl boot 'iPhone 15' || true
          xcrun simctl install booted "$APP_PATH"
          # Start recording, launch app, wait a few seconds, stop
          xcrun simctl io booted recordVideo --codec=h264 app-demo.mp4 &
          REC_PID=$!
          xcrun simctl launch booted com.yourcompany.mood || true
          sleep 8
          kill $REC_PID || true
      - name: Upload simulator video
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: simulator-video
          path: app-demo.mp4
      - name: Run UI snapshot tests
        run: |
          set -euo pipefail
          xcodebuild \
            -project MoodDiary.xcodeproj \
            -scheme MoodDiary \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' \
            -configuration Debug \
            -only-testing:MoodDiaryScreenshots \
            test \
            CODE_SIGNING_ALLOWED=NO \
            | xcpretty -c || true
      - name: Collect snapshots
        run: |
          mkdir -p snapshots
          # Grab all PNGs written by tests
          find /private/var/folders -type f -name '*.png' -maxdepth 6 -print -exec cp -v {} snapshots/ \; 2>/dev/null || true
          ls -la snapshots || true
      - name: Upload snapshots
        uses: actions/upload-artifact@v4
        with:
          name: ui-snapshots
          path: snapshots
